language: node_js
node_js:
  - 10.14
before_install:
  - npm install

script:
  - npm run coverage
# sudo: required
# services:
#   - docker
# before_install:
#   - docker build -t dlinh/react -f Dockerfile.dev .
# script:
#   - docker run -e CI=true dlinh/react npm run test -- --coverage
